name: Release

run-name: Release (${{ inputs.release_type }})

on:
  workflow_call:
    inputs:
      release_type:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        required: true
        options:
          - 'nightly'
          - 'rc'
          - 'stable'

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build-wheel:
    name: Build Wheel for Python ${{ matrix.py }} on linux-x86_64
    uses: ./.github/workflows/build-workflow.yml
    strategy:
      fail-fast: false
      matrix:
        py: ["3.10"]
    with:
      py: ${{ matrix.py }}

  release:
    needs: build-wheel
    permissions: write-all
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: smse-*.whl
        merge-multiple: true
        path: combined-dist
        
    - name: Get package version
      id: get_version
      run: |
        # Extract version from pyproject.toml or setup.py
        if [ -f "pyproject.toml" ]; then
          VERSION=$(grep -m 1 'version = ' pyproject.toml | cut -d '"' -f 2)
        else
          VERSION=$(grep -m 1 'version=' setup.py | cut -d '"' -f 2)
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Create Release Notes
      id: release_notes
      run: |
        cat << EOF > release_notes.md
        
        ## Installation Instructions
        
        Install the latest version:
        \`\`\`bash
        pip install "${{ github.event.repository.name }} @ https://github.com/${{ github.repository }}/releases/latest/download/smse-${{ steps.get_version.outputs.version }}-linx-x86_64.whl"
        \`\`\`
        
        Install this specific version:
        \`\`\`bash
        pip install "${{ github.event.repository.name }} @ https://github.com/${{ github.repository }}/releases/download/v${{ steps.get_version.outputs.version }}/smse-${{ steps.get_version.outputs.version }}-linx-x86_64.whl"
        \`\`\`
        
        ## Available Python Versions
        This release includes builds for:
        - Python 3.10
        - Python 3.11
        - Python 3.12
        - Python 3.13

        EOF
        
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: combined-dist/*
        tag_name: v${{ steps.get_version.outputs.version }}
        name: Release v${{ steps.get_version.outputs.version }}
        body_path: release_notes.md
        generate_release_notes: true
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}